FROM maven:3.9.1-amazoncorretto-17@sha256:979789b8956c72553a1ffe30309cc79a9ab329a23db93103b7d2e63eeac8c0a6 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src /app/src
RUN mvn package -DskipTests
FROM amazoncorretto:8u372-alpine3.17-jre@sha256:d12dd9ad3ac77b69f4e26e34fde77696ca78e5c77c1fdd2bc08065b773287637
WORKDIR /app
RUN addgroup --system javauser
RUN adduser -S -s /bin/false -G javauser javauser
COPY --from=builder /app/target/app-0.0.1-SNAPSHOT.jar /app/application.jar
RUN chown -R javauser:javauser /app
EXPOSE 8080
USER javauser
CMD ["java", "-jar", "application.jar"]